(() => {
  'use strict';
  const TOTAL_ROUNDS = 10;
  const elements = {
    round: document.querySelector('#round'), score: document.querySelector('#score'), runes: document.querySelector('#runes'), combo: document.querySelector('#combo'), streak: document.querySelector('#streak'),
    path: document.querySelector('#rune-path'), instruction: document.querySelector('#instruction'), question: document.querySelector('#question'), targets: document.querySelector('#targets'), arena: document.querySelector('#target-arena'),
    feedback: document.querySelector('#feedback'), comboBanner: document.querySelector('#combo-banner'), shotLayer: document.querySelector('#shot-layer'), next: document.querySelector('.next-question'),
    book: document.querySelector('#living-book'), bookLetters: document.querySelector('#book-letters'), freeze: document.querySelector('#freeze-count'), feather: document.querySelector('#feather-count'), crosshair: document.querySelector('.magic-crosshair'),
    result: document.querySelector('.result-dialog'), guardian: document.querySelector('.guardian-dialog'), reward: document.querySelector('.reward-dialog'), finale: document.querySelector('.finale-dialog'),
    mission: document.querySelector('#mission-screen'), levelScreen: document.querySelector('#level-screen'), levelCards: document.querySelector('#level-cards'), stageName: document.querySelector('#stage-name'), currentLevelName: document.querySelector('#current-level-name'), guardianSecret: document.querySelector('#guardian-secret'), guardianProgress: document.querySelector('#guardian-progress'), bookState: document.querySelector('#book-state'), collection: document.querySelector('#collection-items'), chest: document.querySelector('.chest-dialog'), collectionDialog: document.querySelector('.collection-dialog'), collectionGallery: document.querySelector('#collection-gallery'), levelTransition: document.querySelector('.level-transition')
  };
  let round = 1; let score = 0; let runes = 0; let streak = 0; let bestCombo = 1; let results = []; let deck = []; let currentTask = null;
  let roundActive = false; let shotPending = false; let targetFrame = 0; let targetModels = []; let freezeCharges = 0; let featherCharges = 0; let soundOn = localStorage.getItem('magic-library-sound') !== 'off'; let currentLevel = 1; let currentLevelRepeated = false; let adventurePlan=null; const pointer={x:-9999,y:-9999,active:false};
  const recentIds = new Set(readList('russianRecentQuestionSignatures')); const adventureQuestionSignatures=new Set();
  const audioCache = new Map();
  const victorySong = new Audio('../assets/audio/russian-victory-song.mp3');victorySong.preload='metadata';victorySong.volume=0;victorySong.addEventListener('error',()=>{});
  document.querySelector('#guardian-medal').addEventListener('error',event=>{event.currentTarget.hidden=true;elements.result.classList.add('medal-missing')});
  let victoryFadeFrame=0;let ceremonyRevealed=false;
  const stages = ['Врата букв','Башня слов','Зал орфографии','Лабиринт окончаний','Галерея частей речи','Мост предложений','Башня глаголов','Тайная библиотека','Чернильный зал','Печать Книги'];
  const artifactPool = ['Серебряное Перо','Золотое Перо','Руна Грамматики','Руна Слов','Амулет Орфографии','Кристалл Речи','Тайная Страница'];
  const levels=[
    {id:1,name:'Врата Слов',difficulty:'Начальная',reward:'Золотое Перо Ученика',description:'Научись видеть силу букв и слов.'},
    {id:2,name:'Зал Магических Правил',difficulty:'Средняя',reward:'Амулет Грамматики',description:'Применяй правила в словах и предложениях.'},
    {id:3,name:'Башня Языковых Тайн',difficulty:'Высокая для 4 класса',reward:'Кристалл Живого Слова',description:'Исследуй контекст и языковые закономерности.'},
    {id:4,name:'Тайна Чернильной Тени',difficulty:'Финальная',reward:'Лекса и Легендарная Руна',description:'Сними последнюю печать Книги.'}
  ];

  function randomInt(max){if(globalThis.crypto?.getRandomValues){const value=new Uint32Array(1);crypto.getRandomValues(value);return value[0]%max}return Math.floor((Date.now()+Math.random()*1e9)%max)}
  const pick = items => items[randomInt(items.length)];
  const shuffle = items => { const result = [...items]; for (let i = result.length - 1; i > 0; i -= 1) { const j = randomInt(i + 1); [result[i], result[j]] = [result[j], result[i]]; } return result; };
  const normalized = value => String(value).trim().toLowerCase().replace(/ё/g, 'е');
  function readList(key) { try { const value = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value : []; } catch (_) { return []; } }
  function readObject(key) { try { const value=JSON.parse(localStorage.getItem(key)||'{}'); return value&&typeof value==='object'&&!Array.isArray(value)?value:{} } catch (_) { return {} } }
  function readNumber(key) { const value = Number(localStorage.getItem(key)); return Number.isFinite(value) ? value : 0; }
  function save(key, value) { try { localStorage.setItem(key, String(value)); } catch (_) {} }
  function saveList(key, value) { save(key, JSON.stringify(value)); }
  function task(category, id, instruction, question, answers, correct, explanation) { return { category, id: `${category}:${id}:${question}`, instruction, question, answers: shuffle([...new Set(answers)]), correct, explanation }; }

  const curated = {
    lexicon: [
      task('Лексика','syn-fast','Найди синоним','Синоним к слову «быстрый» — это…',['скорый','медленный','тихий'],'скорый','Синонимы близки по значению.'),
      task('Лексика','ant-brave','Найди антоним','Антоним к слову «смелый» — это…',['храбрый','трусливый','сильный'],'трусливый','Антонимы имеют противоположное значение.'),
      task('Лексика','phrase','Раскрой значение','«Зарубить на носу» означает…',['крепко запомнить','обидеться','записать'],'крепко запомнить','Так говорят о том, что важно запомнить.'),
      task('Лексика','context','Выбери значение по контексту','В предложении «Золотые руки мастера» слово «золотые» означает…',['умелые','жёлтые','дорогие'],'умелые','Это переносное значение слова.'),
      task('Лексика','syn-talk','Найди синоним','Синоним к слову «говорить» — это…',['молчать','беседовать','слушать'],'беседовать','Слова близки по значению.')],
    noun: [
      task('Существительное','case-village','Вставь окончание','Дом стоит около деревн___.',['и','е','я'],'и','Около чего? Родительный падеж: деревни.'),
      task('Существительное','gender','Определи род','Существительное «сирень» какого рода?',['мужского','женского','среднего'],'женского','Сирень — существительное женского рода.'),
      task('Существительное','declension','Определи склонение','Слово «ночь» относится к…',['1-му склонению','2-му склонению','3-му склонению'],'3-му склонению','Женский род с мягким знаком — 3-е склонение.'),
      task('Существительное','case-river','Определи падеж','В сочетании «плыть по реке» слово «реке» стоит в…',['дательном','предложном','творительном'],'дательном','Плыть по чему? Дательный падеж.'),
      task('Существительное','plural','Выбери форму','Форма множественного числа слова «дерево» — …',['деревы','деревья','дерева'],'деревья','Правильная форма: деревья.')],
    adjective: [
      task('Прилагательное','agreement','Согласуй слова','Выбери правильное сочетание.',['весенняя солнце','весеннее солнце','весенний солнце'],'весеннее солнце','Солнце — средний род, единственное число.'),
      task('Прилагательное','ending','Вставь окончание','Мы любовались зимн___ лесом.',['им','ем','ым'],'им','Творительный падеж: зимним лесом.'),
      task('Прилагательное','case','Определи падеж','В сочетании «о далёкой стране» прилагательное стоит в…',['предложном','дательном','родительном'],'предложном','О чём? Предложный падеж.'),
      task('Прилагательное','plural','Выбери форму','К слову «облака» подходит прилагательное…',['лёгкие','лёгкое','лёгкая'],'лёгкие','Облака — множественное число.')],
    pronoun: [
      task('Местоимение','person','Определи лицо','Местоимение «мы» — это…',['1-е лицо','2-е лицо','3-е лицо'],'1-е лицо','Мы — местоимение 1-го лица множественного числа.'),
      task('Местоимение','replace','Устрани повтор','Маша взяла книгу. Маша начала читать. Чем заменить второе слово «Маша»?',['она','они','мы'],'она','Местоимение она устраняет повтор.'),
      task('Местоимение','gender','Определи род','Местоимение «оно» имеет…',['мужской род','женский род','средний род'],'средний род','Оно — местоимение среднего рода.'),
      task('Части речи','adverb','Найди часть речи','«Быстро» — это…',['наречие','глагол','существительное'],'наречие','Слово обозначает признак действия.'),
      task('Части речи','preposition','Найди служебную часть речи','Какое слово является предлогом?',['около','яркий','бежать'],'около','Около — предлог.')],
    verb: [
      task('Глагол','tsya','Вставь окончание','Он старае___ писать аккуратно.',['тся','ться','тсья'],'тся','Что делает? Старается — пишем -тся.'),
      task('Глагол','titsya','Вставь окончание','Нужно стара___ писать аккуратно.',['тся','ться','тсяь'],'ться','Что делать? Стараться — пишем -ться.'),
      task('Глагол','conjugation','Определи спряжение','Глагол «видеть» относится к…',['I спряжению','II спряжению','не имеет спряжения'],'II спряжению','Видеть — глагол-исключение II спряжения.'),
      task('Глагол','ending','Вставь окончание','Дети кле___т модель.',['ят','ют','ять'],'ят','Клеить — II спряжение: они клеят.'),
      task('Глагол','soft','Вставь букву','Ты пишеш___ письмо.',['ь','ъ','без знака'],'ь','После шипящей в глаголе 2-го лица пишется ь.'),
      task('Глагол','not','Выбери написание','Как написать правильно?',['не знал','незнал','не-знал'],'не знал','Не с глаголами пишется раздельно.'),
      task('Глагол','tense','Определи время','Глагол «прочитаю» стоит в…',['прошедшем','настоящем','будущем'],'будущем','Действие ещё произойдёт.')],
    syntax: [
      task('Синтаксис','subject','Найди подлежащее','В предложении «Весной птицы вернулись домой» подлежащее — …',['весной','птицы','вернулись'],'птицы','Кто? Птицы — подлежащее.'),
      task('Синтаксис','predicate','Найди сказуемое','«Яркое солнце осветило поляну». Сказуемое — …',['яркое','солнце','осветило'],'осветило','Что сделало? Осветило — сказуемое.'),
      task('Синтаксис','comma','Выбери знак','На столе лежали книги___ тетради и карандаши.',['запятая','точка','двоеточие'],'запятая','Однородные члены без одиночного союза разделяются запятой.'),
      task('Синтаксис','complex','Определи предложение','Солнце скрылось, и начался дождь. Это предложение…',['простое','сложное','словосочетание'],'сложное','В нём две грамматические основы.'),
      task('Синтаксис','spread','Определи предложение','«Птицы поют». Это предложение…',['распространённое','нераспространённое','сложное'],'нераспространённое','Есть только главные члены.')],
    morpheme: [
      task('Состав слова','root','Найди корень','Какой корень в словах «лес, лесной, лесник»?',['лес','лесн','ник'],'лес','Общая значимая часть — лес.'),
      task('Состав слова','prefix','Найди приставку','Приставка в слове «подлетел» — …',['под','лет','ел'],'под','Приставка стоит перед корнем.'),
      task('Состав слова','suffix','Найди суффикс','Суффикс в слове «берёзка» — …',['берёз','к','а'],'к','Суффикс -к- стоит после корня.'),
      task('Состав слова','ending','Найди окончание','Окончание в слове «книга» — …',['книг','а','иг'],'а','Изменяемая часть слова — окончание -а.'),
      task('Состав слова','base','Найди основу','Основа слова «морской» — …',['мор','морск','ой'],'морск','Основа — слово без окончания.')],
    phonetics: [
      task('Фонетика','stress','Поставь ударение','В каком слове ударение указано верно?',['зво́нит','звони́т','звонит́'],'звони́т','Правильно: звони́т.'),
      task('Фонетика','sounds','Посчитай звуки','Сколько звуков в слове «юла»?',['2','3','4'],'4','Буква ю в начале обозначает два звука [й’у].'),
      task('Фонетика','softness','Найди мягкий согласный','В каком слове первый согласный мягкий?',['мел','мак','мост'],'мел','Звук [м’] перед е — мягкий.'),
      task('Фонетика','letters','Сравни буквы и звуки','В слове «конь»…',['4 буквы, 3 звука','4 буквы, 4 звука','3 буквы, 4 звука'],'4 буквы, 3 звука','Мягкий знак звука не обозначает.')],
    text: [
      task('Текст','type-desc','Определи тип текста','Текст подробно изображает признаки предмета. Это…',['описание','повествование','рассуждение'],'описание','Описание отвечает на вопрос «какой?».') ,
      task('Текст','type-story','Определи тип текста','В тексте события идут одно за другим. Это…',['описание','повествование','рассуждение'],'повествование','Повествование рассказывает о событиях.'),
      task('Текст','main','Найди главную мысль','Главная мысль текста — это…',['то, что хотел сказать автор','первое предложение','самое длинное слово'],'то, что хотел сказать автор','Главная мысль выражает авторский замысел.'),
      task('Текст','keywords','Найди признак','Ключевые слова помогают…',['понять тему текста','посчитать предложения','найти все запятые'],'понять тему текста','Они передают главное содержание.'),
      task('Текст','plan','Выбери порядок','Что помогает восстановить последовательность частей текста?',['план','алфавит','словарь'],'план','Пункты плана отражают порядок частей.')],
    orthography: [
      task('Орфография','vowel','Вставь букву','Тр___ва зеленеет весной.',['а','о','е'],'а','Проверочное слово: травы.'),
      task('Орфография','paired','Вставь букву','На грядке вырос сладкий арбу___.',['з','с','ц'],'з','Проверочное слово: арбузы.'),
      task('Орфография','silent','Вставь букву','Сегодня чудес___ный день.',['т','д','без буквы'],'без буквы','В слове чудесный буква т не пишется.'),
      task('Орфография','dictionary','Выбери слово без ошибки',['инженер','инжинер','инженир'],'инженер','Это словарное слово.'),
      task('Орфография','homophone','Выбери проверочное слово','Проверочное слово для «холо́дный» — …',['хо́лод','холодеет','прохлада'],'хо́лод','Ударение падает на проверяемую гласную.')]
  };

  function generatedOrthography() {
    const samples = [
      ['Он умывае___ утром.','тся','ться','Что делает? Умывается — -тся.'],['Ребята будут учи___ .','ться','тся','Что делать? Учиться — -ться.'],
      ['Мы вид___м далёкие горы.','и','е','Видеть — II спряжение: видим.'],['Ветер гон___т облака.','и','е','Гнать — исключение II спряжения: гонит.']
    ];
    const [question, correct, wrong, explanation] = pick(samples); return task('Орфография',`generated-${question}`, 'Вставь букву или окончание', question, [correct, wrong, `${wrong}ь`], correct, explanation);
  }

  function pickForDifficulty(items,difficulty=1){const size=items.length;if(difficulty===1)return pick(items.slice(0,Math.max(3,Math.ceil(size*.6))));if(difficulty===2)return pick(items.slice(Math.max(0,Math.floor(size*.2))));if(difficulty===3)return pick(items.slice(Math.max(0,Math.floor(size*.35))));return pick(items.slice(Math.max(0,Math.floor(size*.45))))}
  const categoryFactories = {
    orthography: difficulty => difficulty>1&&randomInt(100)<45 ? generatedOrthography() : pickForDifficulty(curated.orthography,difficulty), noun: difficulty => pickForDifficulty(curated.noun,difficulty), lexicon: difficulty => pickForDifficulty(curated.lexicon,difficulty), verb: difficulty => pickForDifficulty(curated.verb,difficulty),
    syntax: difficulty => pickForDifficulty(curated.syntax,difficulty), morpheme: difficulty => pickForDifficulty(curated.morpheme,difficulty), adjective: difficulty => pickForDifficulty(curated.adjective,difficulty), text: difficulty => pickForDifficulty(curated.text,difficulty), pronoun: difficulty => pickForDifficulty(curated.pronoun,difficulty), phonetics: difficulty => pickForDifficulty(curated.phonetics,difficulty)
  };

  function generatePhoneticsTask(difficulty){return categoryFactories.phonetics(difficulty)}function generateStressTask(difficulty){return categoryFactories.phonetics(difficulty)}
  function generateSynonymTask(difficulty){return categoryFactories.lexicon(difficulty)}function generateAntonymTask(difficulty){return categoryFactories.lexicon(difficulty)}function generatePhraseologyTask(difficulty){return categoryFactories.lexicon(difficulty)}
  function generateMorphemeTask(difficulty){return categoryFactories.morpheme(difficulty)}function generateNounGenderTask(difficulty){return categoryFactories.noun(difficulty)}function generateNounCaseTask(difficulty){return categoryFactories.noun(difficulty)}function generateNounDeclensionTask(difficulty){return categoryFactories.noun(difficulty)}function generateNounEndingTask(difficulty){return categoryFactories.noun(difficulty)}
  function generateAdjectiveTask(difficulty){return categoryFactories.adjective(difficulty)}function generateAdjectiveEndingTask(difficulty){return categoryFactories.adjective(difficulty)}function generatePronounTask(difficulty){return categoryFactories.pronoun(difficulty)}
  function generateVerbTenseTask(difficulty){return categoryFactories.verb(difficulty)}function generateVerbPersonTask(difficulty){return categoryFactories.verb(difficulty)}function generateVerbConjugationTask(difficulty){return categoryFactories.verb(difficulty)}function generateVerbEndingTask(difficulty){return categoryFactories.verb(difficulty)}function generateTsyaTask(difficulty){return generatedOrthography(difficulty)}function generateSoftSignVerbTask(difficulty){return categoryFactories.verb(difficulty)}
  function generateAdverbTask(difficulty){return categoryFactories.pronoun(difficulty)}function generatePrepositionPrefixTask(difficulty){return categoryFactories.morpheme(difficulty)}function generateParticleNeTask(difficulty){return categoryFactories.verb(difficulty)}
  function generateSentenceMembersTask(difficulty){return categoryFactories.syntax(difficulty)}function generateSentenceTypeTask(difficulty){return categoryFactories.syntax(difficulty)}function generateHomogeneousMembersTask(difficulty){return categoryFactories.syntax(difficulty)}function generateSimpleComplexTask(difficulty){return categoryFactories.syntax(difficulty)}
  function generateSpellingTask(difficulty){return categoryFactories.orthography(difficulty)}function generatePunctuationTask(difficulty){return categoryFactories.syntax(difficulty)}function generateTextTopicTask(difficulty){return categoryFactories.text(difficulty)}function generateMainIdeaTask(difficulty){return categoryFactories.text(difficulty)}function generateTextOrderTask(difficulty){return categoryFactories.text(difficulty)}function generateReadingTask(difficulty){return categoryFactories.text(difficulty)}
  const balancedGenerators=[generatePhoneticsTask,generateSynonymTask,generateMorphemeTask,generateNounCaseTask,generateAdjectiveTask,generateVerbConjugationTask,generateSpellingTask,generateSentenceMembersTask,generateTextTopicTask,generatePronounTask];
  function normalizeTask(source,difficulty,categoryIndex){const variants=['Прочитай заклинание:','На странице Книги появилось задание:','Открой языковую тайну:','Чернильная Тень оставила вопрос:','Восстанови правило:','Хранитель просит ответить:','Руна проверяет знания:','Продолжи путь:'],variant=randomInt(variants.length),answers=shuffle([...source.answers]),correctIndex=answers.findIndex(answer=>normalized(answer)===normalized(source.correct));return{...source,id:source.id,signature:`${source.id}|form-${variant}`,category:source.category,subcategory:source.id.split(':')[1]||`topic-${categoryIndex}`,difficulty,question:`${variants[variant]} ${source.question}`,answers,correctIndex,correct:answers[correctIndex]}}
  function validateTask(candidate){return Boolean(candidate&&candidate.question&&candidate.signature&&candidate.explanation&&candidate.difficulty>=1&&candidate.difficulty<=4&&Array.isArray(candidate.answers)&&candidate.answers.length===3&&new Set(candidate.answers.map(normalized)).size===3&&Number.isInteger(candidate.correctIndex)&&candidate.correctIndex>=0&&candidate.correctIndex<3)}
  function sessionFingerprint(tasks){return tasks.map(item=>item.signature).sort().join('|')}
  function generateNewSession(level){const fingerprints=readList('russianRecentSessionFingerprints');for(let sessionAttempt=0;sessionAttempt<8;sessionAttempt+=1){const session=new Set(),tasks=[];const generators=shuffle(balancedGenerators);for(let index=0;index<TOTAL_ROUNDS;index+=1){let candidate=null;for(let attempt=0;attempt<80;attempt+=1){const raw=generators[index](level),normalizedTask=normalizeTask(raw,level,index);if(validateTask(normalizedTask)&&!session.has(normalizedTask.signature)&&!adventureQuestionSignatures.has(normalizedTask.signature)&&(!recentIds.has(normalizedTask.signature)||attempt>65)){candidate=normalizedTask;break}}if(!candidate){const raw=generators[index](level);candidate=normalizeTask(raw,level,index);candidate.signature=`${candidate.signature}|seed-${Date.now()}-${index}-${sessionAttempt}`}session.add(candidate.signature);tasks.push(candidate)}const fingerprint=sessionFingerprint(tasks);if(!fingerprints.includes(fingerprint)){session.forEach(signature=>adventureQuestionSignatures.add(signature));const history=[...recentIds,...session].slice(-280);saveList('russianRecentQuestionSignatures',history);recentIds.clear();history.forEach(signature=>recentIds.add(signature));saveList('russianRecentSessionFingerprints',[...fingerprints,fingerprint].slice(-40));return tasks}}return []}

  async function playSound(name) {
    if (!soundOn) return; if (audioCache.has(name)) { const cached = audioCache.get(name); if (cached) { cached.currentTime = 0; await cached.play().catch(() => {}); } return; }
    audioCache.set(name, null); try { const path = `../assets/audio/russian-${name}.mp3`; const response = await fetch(path,{method:'HEAD',cache:'force-cache'}); if (!response.ok) return; const audio = new Audio(path); audio.volume=.42; audioCache.set(name,audio); await audio.play().catch(()=>{}); } catch (_) {}
  }
  function fadeVictoryOut(reset=true){cancelAnimationFrame(victoryFadeFrame);const start=victorySong.volume,started=performance.now();const fade=now=>{const progress=Math.min(1,(now-started)/750);victorySong.volume=Math.max(0,start*(1-progress));if(progress<1)victoryFadeFrame=requestAnimationFrame(fade);else{victorySong.pause();if(reset)try{victorySong.currentTime=0}catch(_){}}};victoryFadeFrame=requestAnimationFrame(fade)}
  function startVictorySong(reset=true){if(!soundOn||!ceremonyRevealed)return;cancelAnimationFrame(victoryFadeFrame);if(reset)try{victorySong.currentTime=0}catch(_){}victorySong.volume=0;victorySong.play().then(()=>{const started=performance.now();const fade=now=>{const progress=Math.min(1,(now-started)/1000);victorySong.volume=.4*progress;if(progress<1&&soundOn&&ceremonyRevealed)victoryFadeFrame=requestAnimationFrame(fade)};victoryFadeFrame=requestAnimationFrame(fade)}).catch(()=>{})}
  function createCeremonyParticles(legendary=false){const layer=document.querySelector('#ceremony-particles');layer.replaceChildren();const count=legendary?20:14;for(let index=0;index<count;index+=1){const particle=document.createElement('i');particle.textContent=index%4===0?pick(['А','Я','Б','◇']):'';particle.style.setProperty('--particle-x',`${8+Math.random()*84}%`);particle.style.setProperty('--particle-y',`${12+Math.random()*72}%`);particle.style.setProperty('--particle-delay',`${Math.random()*.45}s`);particle.style.setProperty('--particle-drift',`${(Math.random()-.5)*70}px`);layer.append(particle);particle.addEventListener('animationend',()=>particle.remove(),{once:true})}}

  function updateHud() {
    elements.round.textContent = `${round} / ${TOTAL_ROUNDS}`; elements.score.textContent = score.toLocaleString('ru-RU'); elements.runes.textContent = runes; const multiplier = streak >= 5 ? 3 : streak >= 3 ? 2 : 1; elements.combo.textContent = `×${multiplier}`; elements.streak.textContent = streak; elements.freeze.textContent = '∞'; elements.feather.textContent = featherCharges;document.querySelector('.use-feather').disabled=!roundActive||shotPending||featherCharges<1;
    elements.book.style.setProperty('--book-energy', runes / TOTAL_ROUNDS); elements.book.dataset.level = runes >= 10 ? '10' : runes >= 7 ? '7' : runes >= 5 ? '5' : runes >= 3 ? '3' : '0'; elements.bookLetters.textContent = 'АБВГДЕЖЗИК'.slice(0,runes).split('').join(' '); elements.stageName.textContent=stages[Math.min(round-1,9)];elements.currentLevelName.textContent=levels[currentLevel-1].name;
    const baseReveal=[0,.25,.5,.85][currentLevel-1],levelReveal=runes>=10?1:runes>=7?.75:runes>=5?.5:runes>=3?.25:0,reveal=Math.max(baseReveal,levelReveal);elements.guardianSecret.style.setProperty('--reveal',reveal);elements.guardianSecret.classList.toggle('revealed',reveal>0);elements.guardianProgress.textContent=`${Math.round(reveal*100)}%`;elements.bookState.textContent=runes>=10?'Книга полностью пробудилась!':runes>=7?'Страницы сияют живым словом':runes>=5?'Книга начинает открываться':runes>=3?'Появились золотые письмена':runes>0?'На обложке появились слабые письмена':'Книга ждёт свои руны';
    document.body.classList.toggle('final-chapter',round>=8);document.querySelectorAll('.reward-road span').forEach(item=>{const point=Number(item.dataset.milestone);const opened=runes>=point;item.classList.toggle('unlocked',opened);item.querySelector('i').textContent=opened?(point===3?'Золотое перо':point===5?'Тайная страница':point===7?'Амулет':'Большой секрет'):'?'});renderPath();
  }
  function renderPath(){elements.path.replaceChildren();for(let i=0;i<TOTAL_ROUNDS;i+=1){const rune=document.createElement('i');rune.dataset.step=i+1;rune.title=stages[i];rune.className=results[i]===true?'correct':results[i]===false?'missed':i===round-1?'current':'';rune.setAttribute('aria-label',`${i+1}. ${stages[i]}${results[i]===true?': руна найдена':results[i]===false?': пройдено':''}`);elements.path.append(rune)}}

  function flyRune(target){if(!target)return;const from=target.getBoundingClientRect(),to=elements.book.getBoundingClientRect(),rune=document.createElement('i');rune.className='rune-flight';rune.style.left=`${from.left+from.width/2}px`;rune.style.top=`${from.top+from.height/2}px`;rune.style.setProperty('--to-x',`${to.left+to.width/2}px`);rune.style.setProperty('--to-y',`${to.top+to.height/2}px`);document.body.append(rune);setTimeout(()=>{rune.remove();elements.book.classList.remove('book-rune-burst');void elements.book.offsetWidth;elements.book.classList.add('book-rune-burst')},780)}
  function addArtifact(name){const artifacts=readList('russianArtifacts');if(!artifacts.includes(name)){artifacts.push(name);saveList('russianArtifacts',artifacts)}return artifacts}

  function createTargets() {
    elements.targets.replaceChildren();elements.targets.classList.remove('answered');targetModels=[];const bounds=elements.targets.getBoundingClientRect(),mobile=innerWidth<=700;currentTask.answers.forEach((answer,index)=>{const button=document.createElement('button');button.type='button';button.className='answer-target';button.textContent=answer;button.dataset.answer=answer;button.dataset.answerId=index;button.dataset.targetId=`answer-${currentLevel}-${round}-${index}`;button.setAttribute('aria-label',`Ответ ${index+1}: ${answer}`);elements.targets.append(button);const zoneWidth=mobile?bounds.width:bounds.width/3,zoneHeight=bounds.height/3,baseX=mobile?(bounds.width-button.offsetWidth)/2:index*zoneWidth+(zoneWidth-button.offsetWidth)/2,baseY=mobile?index*zoneHeight+(zoneHeight-button.offsetHeight)/2:bounds.height*.42-button.offsetHeight/2;targetModels.push({element:button,x:baseX,y:baseY,baseX,baseY,vx:(index%2?1:-1)*.055,vy:(index===1?-.045:.04),phase:Math.random()*6.28,frozen:false,rangeX:mobile?10:Math.max(8,zoneWidth/2-button.offsetWidth/2-26),rangeY:mobile?8:42});});
  }
  function proximityFor(model){if(!pointer.active||innerWidth<=700)return 1;const rect=model.element.getBoundingClientRect(),inside=pointer.x>=rect.left-20&&pointer.x<=rect.right+20&&pointer.y>=rect.top-20&&pointer.y<=rect.bottom+20;model.element.classList.toggle('aimed',inside);model.element.classList.remove('near-target');return inside ? .3 : 1}
  function separateTargets(bounds){const hitGap=46;for(let pass=0;pass<2;pass+=1){for(let i=0;i<targetModels.length;i+=1){for(let j=i+1;j<targetModels.length;j+=1){const a=targetModels[i],b=targetModels[j],ax=a.x+a.element.offsetWidth/2,ay=a.y+a.element.offsetHeight/2,bx=b.x+b.element.offsetWidth/2,by=b.y+b.element.offsetHeight/2,dx=bx-ax,dy=by-ay,overlapX=(a.element.offsetWidth+b.element.offsetWidth)/2+hitGap-Math.abs(dx),overlapY=(a.element.offsetHeight+b.element.offsetHeight)/2+hitGap-Math.abs(dy);if(overlapX>0&&overlapY>0){if(overlapX<overlapY){const direction=dx>=0?1:-1;a.x-=direction*overlapX/2;b.x+=direction*overlapX/2;a.vx*=-1;b.vx*=-1}else{const direction=dy>=0?1:-1;a.y-=direction*overlapY/2;b.y+=direction*overlapY/2;a.vy*=-1;b.vy*=-1}}}}}targetModels.forEach(model=>{model.x=Math.max(0,Math.min(model.x,bounds.width-model.element.offsetWidth));model.y=Math.max(0,Math.min(model.y,bounds.height-model.element.offsetHeight))})}
  function animateTargets(time){if(!roundActive)return;targetModels.forEach(model=>{if(!model.frozen){const slow=proximityFor(model);model.x+=model.vx*slow;model.y+=model.vy*slow+Math.sin(time/1250+model.phase)*.012*slow;if(model.x<model.baseX-model.rangeX||model.x>model.baseX+model.rangeX)model.vx*=-1;if(model.y<model.baseY-model.rangeY||model.y>model.baseY+model.rangeY)model.vy*=-1;model.x=Math.max(model.baseX-model.rangeX,Math.min(model.x,model.baseX+model.rangeX));model.y=Math.max(model.baseY-model.rangeY,Math.min(model.y,model.baseY+model.rangeY))}model.element.style.transform=`translate3d(${model.x}px,${model.y}px,0)`});targetFrame=requestAnimationFrame(animateTargets)}

  function startRound(){roundActive=true;shotPending=false;currentTask=deck[round-1];elements.instruction.textContent=round===10?'ФИНАЛЬНОЕ ИСПЫТАНИЕ':currentTask.instruction;elements.question.textContent=currentTask.question;elements.feedback.classList.remove('show');elements.comboBanner.classList.remove('show');elements.next.hidden=true;document.body.classList.toggle('final-trial',round===10);createTargets();updateHud();cancelAnimationFrame(targetFrame);requestAnimationFrame(animateTargets)}

  function impactSparkles(x,y,correct){const count=innerWidth<=700?3:6;for(let i=0;i<count;i+=1){const p=document.createElement('b');p.className=`shot-particle${correct===false?' ink':''}`;p.style.left=`${x}px`;p.style.top=`${y}px`;p.style.setProperty('--dx',`${(Math.random()-.5)*78}px`);p.style.setProperty('--dy',`${(Math.random()-.65)*78}px`);elements.shotLayer.append(p);p.addEventListener('animationend',()=>p.remove(),{once:true})}}
  function createShot(clientX,clientY,onImpact){const arena=elements.arena.getBoundingClientRect(),quillElement=document.querySelector('#quill-blaster'),quill=quillElement.getBoundingClientRect(),x1=quill.left+quill.width/2-arena.left,y1=quill.top+18-arena.top,x2=clientX-arena.left,y2=clientY-arena.top,dx=x2-x1,dy=y2-y1;quillElement.classList.remove('charging');void quillElement.offsetWidth;quillElement.classList.add('charging');playSound('charge');const projectile=document.createElement('i');projectile.className='magic-projectile';projectile.style.left=`${x1}px`;projectile.style.top=`${y1}px`;projectile.style.setProperty('--shot-x',`${dx}px`);projectile.style.setProperty('--shot-y',`${dy}px`);projectile.style.setProperty('--shot-angle',`${Math.atan2(dy,dx)}rad`);elements.shotLayer.append(projectile);requestAnimationFrame(()=>{projectile.classList.add('flying');playSound('shot');playSound('projectile')});projectile.addEventListener('animationend',()=>{projectile.remove();impactSparkles(x2,y2);onImpact?.()},{once:true})}
  function burstLetters(target){if(!target)return;const arena=elements.arena.getBoundingClientRect(),rect=target.getBoundingClientRect(),letters='АБВГДЕЖЗ'.split(''),count=innerWidth<=700?4:7;for(let i=0;i<count;i+=1){const particle=document.createElement('b');particle.className='letter-particle';particle.textContent=pick(letters);particle.style.left=`${rect.left+rect.width/2-arena.left}px`;particle.style.top=`${rect.top+rect.height/2-arena.top}px`;particle.style.setProperty('--dx',`${(Math.random()-.5)*115}px`);particle.style.setProperty('--dy',`${(Math.random()-.7)*100}px`);elements.shotLayer.append(particle);particle.addEventListener('animationend',()=>particle.remove(),{once:true})}}
  function showFeedback(title,copy){elements.feedback.innerHTML=`<strong>${title}</strong><small>${copy}</small>`;elements.feedback.classList.remove('show');void elements.feedback.offsetWidth;elements.feedback.classList.add('show')}
  function showCombo(){if(streak===3)elements.comboBanner.textContent='КОМБО ×2';else if(streak===5){elements.comboBanner.textContent='МАСТЕР СЛОВ ×3 · ЗОЛОТОЕ ПЕРО';if(featherCharges<1)featherCharges=1}else return;elements.comboBanner.classList.remove('show');void elements.comboBanner.offsetWidth;elements.comboBanner.classList.add('show');playSound('combo')}
  function finishAnswer(correct,target){if(!roundActive)return;roundActive=false;cancelAnimationFrame(targetFrame);targetModels.forEach(model=>model.frozen=true);elements.targets.classList.add('answered');results.push(correct);if(correct){streak+=1;const multiplier=streak>=5?3:streak>=3?2:1;score+=100*multiplier;runes+=1;target?.classList.add('hit-correct');burstLetters(target);const remaining=TOTAL_ROUNDS-round,motivation=remaining===3?' До сундука осталось 3 испытания!':remaining===1?' Последнее испытание перед сундуком!':'';setTimeout(()=>{flyRune(target);showFeedback('РУНА НАЙДЕНА!',`${currentTask.explanation}${motivation}`);showCombo();playSound('correct');playSound('rune')},180)}else{streak=0;target?.classList.add('hit-wrong');const right=[...elements.targets.children].find(item=>normalized(item.dataset.answer)===normalized(currentTask.correct));right?.classList.add('golden-hint');setTimeout(()=>{showFeedback('Почти!',`Правильный ответ: ${currentTask.correct}. ${currentTask.explanation}`);playSound('wrong')},140)}bestCombo=Math.max(bestCombo,streak>=5?3:streak>=3?2:1);updateHud();setTimeout(()=>{elements.next.hidden=false;elements.next.focus()},correct?220:180)}
  function nextRound(){if(round>=TOTAL_ROUNDS){completeGame();return}round+=1;startRound()}

  function showMiss(clientX,clientY){const arena=elements.arena.getBoundingClientRect(),message=document.createElement('span');message.className='miss-message';message.textContent='Мимо! Попробуй ещё раз';message.style.left=`${clientX-arena.left}px`;message.style.top=`${clientY-arena.top}px`;elements.shotLayer.append(message);message.addEventListener('animationend',()=>message.remove(),{once:true});playSound('miss')}
  function shootAt(clientX,clientY,target){if(!roundActive||shotPending)return;const validTarget=target&&!target.classList.contains('eliminated')?target:null;if(validTarget){shotPending=true;validTarget.classList.add('shot-locked');targetModels.forEach(model=>model.frozen=true)}else shotPending=true;createShot(clientX,clientY,()=>{if(!validTarget){showMiss(clientX,clientY);shotPending=false;updateHud();return}playSound('hit');const isCorrect=normalized(validTarget.dataset.answer)===normalized(currentTask.correct);validTarget.classList.add('target-impact',isCorrect?'impact-correct':'impact-wrong');finishAnswer(isCorrect,validTarget)})}
  elements.arena.addEventListener('pointerdown',event=>{if(event.button!==undefined&&event.button!==0)return;if(event.target.closest('.next-question'))return;const target=document.elementsFromPoint(event.clientX,event.clientY).map(node=>node.closest?.('.answer-target')).find(Boolean);shootAt(event.clientX,event.clientY,target)});
  elements.targets.addEventListener('click',event=>{if(event.detail!==0)return;const target=event.target.closest('.answer-target');if(!target)return;const rect=target.getBoundingClientRect();shootAt(rect.left+rect.width/2,rect.top+rect.height/2,target)});

  let pendingChest={reward:'',first:false,next:0};
  function completedLevels(){return readList('russianCompletedLevels').map(Number)}
  function updateLevelRecords(){const scores=readObject('russianBestScoreByLevel'),correct=readObject('russianBestCorrectByLevel');scores[currentLevel]=Math.max(Number(scores[currentLevel])||0,score);correct[currentLevel]=Math.max(Number(correct[currentLevel])||0,runes);save('russianBestScoreByLevel',JSON.stringify(scores));save('russianBestCorrectByLevel',JSON.stringify(correct));save('russianBestCombo',Math.max(bestCombo,readNumber('russianBestCombo')))}
  function shardsForResult(){return runes===10?5:runes===9?3:runes===8?2:1}
  function completeGame(){roundActive=false;document.body.classList.remove('final-trial');updateLevelRecords();if(runes<7){openResult(false,'');return}const completed=completedLevels(),first=!completed.includes(currentLevel);if(first){completed.push(currentLevel);saveList('russianCompletedLevels',completed.sort());save('russianHighestUnlockedLevel',Math.min(4,Math.max(readNumber('russianHighestUnlockedLevel')||1,currentLevel+1)));const rewards=readObject('russianLevelRewards');rewards[currentLevel]=levels[currentLevel-1].reward;save('russianLevelRewards',JSON.stringify(rewards));addArtifact(levels[currentLevel-1].reward);if(currentLevel===4){save('russianGuardianUnlocked','true');['Лекса — Хранительница Слов','Легендарная Руна Слов','Титул: Мастер Академии Слов'].forEach(addArtifact)}}else{const shards=readNumber('russianMagicShards')+shardsForResult();save('russianMagicShards',shards);if(shards>=10&&localStorage.getItem('russianInkFamiliarUnlocked')!=='true'){save('russianInkFamiliarUnlocked','true');addArtifact('Чернильный Фамильяр')}}pendingChest={reward:first?levels[currentLevel-1].reward:`Осколки Магии +${shardsForResult()}`,first,next:first&&currentLevel<4?currentLevel+1:0};playSound('level-complete');if(currentLevel===4){elements.finale.showModal()}else showChest()}
  function showChest(){ceremonyRevealed=false;fadeVictoryOut();document.querySelector('#chest-title').textContent='ИСПЫТАНИЕ ПРОЙДЕНО!';document.querySelector('#chest-reward').textContent='ТВОЯ НАГРАДА';document.querySelector('#chest-copy').textContent='Ты вернул руны слов и открыл ещё одну тайну Академии.';document.querySelector('#level-unlocked-copy').textContent=pendingChest.next?`Путь дальше открыт: ${levels[pendingChest.next-1].name}`:currentLevel===4?'Последняя печать снята!':'';elements.chest.classList.toggle('legendary',runes===10);elements.chest.showModal();playSound('chest-open')}
  function ratingName(){return runes===10?'ЛЕГЕНДАРНАЯ РУНА СЛОВ':runes>=8?'СИЯЮЩАЯ РУНА':'СЕРЕБРЯНАЯ РУНА'}
  function medalForResult(){return runes===10?{key:'guardian',name:'ЛЕГЕНДАРНАЯ МЕДАЛЬ ХРАНИТЕЛЯ',theme:'legendary'}:runes===9?{key:'wordMaster',name:'МЕДАЛЬ МАСТЕРА СЛОВ',theme:'master'}:runes===8?{key:'rulesExpert',name:'МЕДАЛЬ ЗНАТОКА ПРАВИЛ',theme:'expert'}:{key:'seeker',name:'МЕДАЛЬ ИСКАТЕЛЯ СЛОВ',theme:'seeker'}}
  function openResult(won){const medal=medalForResult(),medals=readObject('russianAchievementMedals'),isNew=won&&!medals[medal.key];if(isNew){medals[medal.key]=true;save('russianAchievementMedals',JSON.stringify(medals))}ceremonyRevealed=won;elements.result.className=`game-dialog result-dialog${won?` ceremony-${medal.theme}`:' ceremony-failed'}`;document.querySelector('#achievement-state').textContent=won?(isNew?'НОВОЕ ДОСТИЖЕНИЕ!':'МЕДАЛЬ ПОДТВЕРЖДЕНА!'):'ИСПЫТАНИЕ ЗАВЕРШЕНО';document.querySelector('#result-title').textContent=won?'ТВОЯ НАГРАДА':'ПЕЧАТЬ ПОЧТИ ПОДДАЛАСЬ';document.querySelector('#result-copy').textContent=won?(isNew?'Медаль добавлена в твою Коллекцию Академии.':'Ты подтвердил своё мастерство и открыл ещё одну тайну Академии!'):`Ты вернул ${runes} из 10 рун. До открытия следующего уровня не хватило ${7-runes}.`;document.querySelector('#result-correct').textContent=`${runes} / 10`;document.querySelector('#result-score').textContent=score.toLocaleString('ru-RU');document.querySelector('#result-combo').textContent=`×${bestCombo}`;document.querySelector('#reward-name').textContent=won?medal.name:'ПОПРОБУЙ ЕЩЁ РАЗ';document.querySelector('#feather-total').textContent=won?`+${pendingChest.first?0:shardsForResult()}`:'—';document.querySelector('.ceremony-continue').hidden=!won;document.querySelector('.collection-saved').hidden=!won;document.querySelector('.result-collection-button').hidden=!won;document.querySelector('#guardian-medal').hidden=!won;createCeremonyParticles(won&&runes===10);elements.result.showModal()}
  const rewardIcons=['feather','amulet','crystal','rune','guardian'];
  function rewardCard(name,index,owned){return `<i class="artifact-icon ${rewardIcons[index]}"></i><strong>${owned?name:'???'}</strong><small>${owned?'Найдено':'Тайна ещё закрыта'}</small>`}
  function renderCollectionGallery(){const artifacts=readList('russianArtifacts'),names=['Золотое Перо Ученика','Амулет Грамматики','Кристалл Живого Слова','Легендарная Руна Слов','Лекса — Хранительница Слов'];elements.collectionGallery.replaceChildren();names.forEach((name,index)=>{const owned=artifacts.some(item=>item===name||(index===4&&item.includes('Лекса'))),item=document.createElement('article');item.className=`gallery-artifact${owned?' owned':' locked'}`;item.innerHTML=rewardCard(name,index,owned);elements.collectionGallery.append(item)});const medals=readObject('russianAchievementMedals');[{key:'seeker',name:'Медаль Искателя Слов'},{key:'rulesExpert',name:'Медаль Знатока Правил'},{key:'wordMaster',name:'Медаль Мастера Слов'},{key:'guardian',name:'Легендарная Медаль Хранителя'}].forEach(medal=>{const owned=Boolean(medals[medal.key]),item=document.createElement('article');item.className=`gallery-artifact gallery-medal${owned?' owned':' locked'}`;item.innerHTML=`<img src="../assets/russian-rewards/guardian-medal.png" alt="" width="1254" height="1254"><strong>${owned?medal.name:'???'}</strong><small>${owned?'Получена':'Медаль ещё не открыта'}</small>`;elements.collectionGallery.append(item)})}
  function renderLevelScreen(){const highest=Math.max(1,readNumber('russianHighestUnlockedLevel')||1),completed=completedLevels(),scores=readObject('russianBestCorrectByLevel'),rewards=readObject('russianLevelRewards');elements.levelCards.replaceChildren();levels.forEach(level=>{const locked=level.id>highest,card=document.createElement('button');card.type='button';card.className=`level-card level-${level.id}${completed.includes(level.id)?' completed':''}${level.id===highest?' current':''}${locked?' locked':''}`;card.disabled=locked;card.dataset.level=level.id;card.innerHTML=`<span class="level-number">${level.id}</span><div class="level-scene" aria-hidden="true"><img src="../assets/russian-levels/level-${level.id}-${['gates','library','tower','shadow'][level.id-1]}.png" alt="" width="1448" height="1086"><span class="scene-light"></span><span class="scene-mist"></span><span class="scene-letter letter-a">А</span><span class="scene-letter letter-ya">Я</span><span class="scene-letter letter-rune">◇</span><span class="scene-spark spark-1"></span><span class="scene-spark spark-2"></span><span class="scene-spark spark-3"></span><span class="scene-spark spark-4"></span><span class="scene-spark spark-5"></span></div><div class="level-copy"><small>Уровень ${level.id} · ${level.difficulty}</small><h3>${level.name}</h3><span class="best-score">Лучший результат: ${scores[level.id]||0} / 10</span><span class="level-reward"><i class="artifact-icon ${rewardIcons[Math.min(level.id-1,3)]}"></i>${locked?'ТАЙНА ЕЩЁ ЗАКРЫТА':rewards[level.id]||level.reward}</span></div>${locked?'<span class="locked-caption">ТАЙНА ЕЩЁ ЗАКРЫТА</span><span class="magic-lock" aria-hidden="true">◇</span>':''}`;elements.levelCards.append(card)});const slots=document.querySelector('#adventure-reward-slots');slots.replaceChildren();['Золотое Перо','Амулет Грамматики','Кристалл Живого Слова','Легендарная Руна','Секретный Хранитель'].forEach((name,index)=>{const owned=index<3?completed.includes(index+1):completed.includes(4),slot=document.createElement('article');slot.className=`reward-slot${owned?' owned':' locked'}`;slot.innerHTML=rewardCard(name,index,owned);slots.append(slot)});const shards=readNumber('russianMagicShards'),progress=RussianCurriculumEngine.getCoverageProgress();document.querySelector('#campaign-shards-label').textContent=`Осколки магии: ${Math.min(shards,10)} / 10${localStorage.getItem('russianInkFamiliarUnlocked')==='true'?' · Фамильяр открыт':''}`;document.querySelector('#campaign-shards-bar').style.width=`${Math.min(shards*10,100)}%`;document.querySelector('#curriculum-progress-label').textContent=progress.complete?'Все тайны курса исследованы!':`Исследовано тайн языка: ${progress.encountered} / ${progress.total} (${progress.percent}%)`;document.querySelector('#curriculum-progress-bar').style.width=`${progress.percent}%`;renderCollectionGallery()}
  function showLevelScreen(){roundActive=false;ceremonyRevealed=false;fadeVictoryOut();cancelAnimationFrame(targetFrame);[elements.result,elements.chest,elements.guardian].forEach(dialog=>{if(dialog.open)dialog.close()});renderLevelScreen();elements.levelScreen.classList.remove('hidden')}
  function createNewAdventure(){adventureQuestionSignatures.clear();adventurePlan=RussianCurriculumEngine.buildAdventureCurriculumPlan();showLevelScreen()}
  function startLevel(level,forceFresh=false){currentLevel=level;currentLevelRepeated=completedLevels().includes(level);pendingChest={reward:'',first:false,next:0};round=1;score=0;runes=0;streak=0;bestCombo=1;results=[];freezeCharges=0;featherCharges=readList('russianArtifacts').includes('Золотое Перо Ученика')?1:0;deck=!forceFresh&&adventurePlan?.levels?.[level]?adventurePlan.levels[level]:RussianCurriculumEngine.generateLevel(level);const progress=RussianCurriculumEngine.commitTasks(deck);if(progress.complete&&localStorage.getItem('russianCurriculumMasteryRewardUnlocked')==='true')addArtifact('Кристалл Знатока Языка');elements.levelScreen.classList.add('hidden');document.body.classList.toggle('final-chapter',level===4);startRound()}
  function enterLevel(card){const level=Number(card.dataset.level);if(!level||card.disabled)return;card.classList.add('departing');showMagicTransition({theme:'russian',title:levels[level-1].name.toUpperCase(),subtitle:'Новое языковое испытание начинается!',onComplete:()=>{startLevel(level,completedLevels().includes(level));card.classList.remove('departing')}})}
  function resetGame(){startLevel(currentLevel,true)}

  const help=document.querySelector('.help-dialog');document.querySelector('.help-button').addEventListener('click',()=>help.showModal());document.querySelector('.help-dialog .dialog-close').addEventListener('click',()=>help.close());document.querySelector('.dialog-action').addEventListener('click',()=>help.close());document.querySelector('.mission-start').addEventListener('click',()=>{save('russianCampaignSeen','true');elements.mission.classList.add('hidden');createNewAdventure()});elements.levelCards.addEventListener('click',event=>{const card=event.target.closest('.level-card');if(card&&!card.disabled)enterLevel(card)});document.querySelector('.collection-button').addEventListener('click',()=>{renderCollectionGallery();elements.collectionDialog.showModal()});document.querySelector('.collection-close').addEventListener('click',()=>elements.collectionDialog.close());elements.next.addEventListener('click',nextRound);document.querySelector('.use-feather').addEventListener('click',()=>{if(!roundActive||shotPending||featherCharges<1)return;const wrong=[...elements.targets.children].filter(item=>normalized(item.dataset.answer)!==normalized(currentTask.correct)&&!item.classList.contains('eliminated'));const target=pick(wrong);if(target){target.classList.add('eliminated');target.setAttribute('aria-disabled','true');featherCharges-=1;updateHud()}});document.querySelector('.finale-continue').addEventListener('click',()=>{elements.finale.close();showChest()});document.querySelector('.claim-reward').addEventListener('click',()=>{elements.chest.close();playSound('reward');openResult(true);startVictorySong(true)});document.querySelector('.replay-button').addEventListener('click',()=>{ceremonyRevealed=false;fadeVictoryOut();elements.result.close();resetGame()});document.querySelector('.ceremony-continue').addEventListener('click',()=>{ceremonyRevealed=false;fadeVictoryOut();elements.result.close();if(currentLevel===4&&pendingChest.first){elements.guardian.showModal();playSound('guardian-reveal')}else showLevelScreen()});document.querySelector('.result-collection-button').addEventListener('click',()=>{renderCollectionGallery();elements.collectionDialog.showModal()});document.querySelector('.guardian-continue').addEventListener('click',()=>{elements.guardian.close();showLevelScreen()});[elements.guardian,elements.result,elements.chest,elements.finale].forEach(dialog=>dialog.addEventListener('cancel',event=>event.preventDefault()));
  const soundButton=document.querySelector('.sound-button');function renderSound(){soundButton.textContent=soundOn?'🔊':'🔇';soundButton.setAttribute('aria-pressed',String(soundOn));soundButton.setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук')}soundButton.addEventListener('click',()=>{soundOn=!soundOn;save('magic-library-sound',soundOn?'on':'off');AdventureMusic.syncWithSoundSetting();if(!soundOn)fadeVictoryOut(false);else if(ceremonyRevealed&&elements.result.open)startVictorySong(false);renderSound()});AdventureMusic.configure(.095);renderSound();
  if(matchMedia('(hover:hover) and (pointer:fine)').matches){document.body.classList.add('crosshair-active');document.addEventListener('pointermove',event=>{pointer.x=event.clientX;pointer.y=event.clientY;pointer.active=true;const inside=Boolean(document.elementsFromPoint(event.clientX,event.clientY).some(node=>node===elements.arena||node.closest?.('#target-arena')));elements.crosshair.classList.toggle('visible',inside);elements.crosshair.style.transform=`translate3d(${event.clientX}px,${event.clientY}px,0)`;if(inside){const blaster=document.querySelector('#quill-blaster').getBoundingClientRect(),angle=Math.atan2(event.clientY-(blaster.top+blaster.height),event.clientX-(blaster.left+blaster.width/2))*180/Math.PI+90;document.querySelector('#quill-blaster').style.setProperty('--aim-angle',`${Math.max(-18,Math.min(18,angle))}deg`)}} ,{passive:true});document.addEventListener('pointerleave',()=>{pointer.active=false;elements.crosshair.classList.remove('visible');targetModels.forEach(model=>model.element.classList.remove('aimed','near-target'))})}
  save('russianHighestUnlockedLevel',Math.max(1,readNumber('russianHighestUnlockedLevel')));if(localStorage.getItem('russianCampaignSeen')==='true'){elements.mission.classList.add('hidden');createNewAdventure()}else{updateHud()}
})();
