(() => {
  'use strict';
  const $=selector=>document.querySelector(selector),read=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key)||'null');return value??fallback}catch(_){return fallback}},write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch(_){}};
  const mapScreen=$('#map-screen'),missionScreen=$('#mission-screen'),territories=$('#territories'),interaction=$('#interaction-zone'),feedback=$('#mission-feedback'),continueButton=$('.continue-mission');
  const levelMeta=[
    {name:'Россия на карте',image:'level-1-russia.png',postcard:'МОЯ РОССИЯ',medal:'МЕДАЛЬ ЮНОГО КАРТОГРАФА',medalImage:'medal-cartographer.png'},
    {name:'Машина времени',image:'level-2-history.png',postcard:'СКВОЗЬ ВЕКА',medal:'МЕДАЛЬ ХРАНИТЕЛЯ ИСТОРИИ',medalImage:'medal-history.png'},
    {name:'Планета чудес',image:'level-3-nature.png',postcard:'ПЛАНЕТА ЧУДЕС',medal:'МЕДАЛЬ ИССЛЕДОВАТЕЛЯ ПРИРОДЫ',medalImage:'medal-nature.png'},
    {name:'Миссия спасателей',image:'level-4-safety.png',postcard:'ГЕРОЙ ЭКСПЕДИЦИИ',medal:'ЛЕГЕНДАРНАЯ МЕДАЛЬ ВЕЛИКОГО ИССЛЕДОВАТЕЛЯ',medalImage:'medal-explorer.png'}
  ];
  const mechanicNames={'hotspot':'Найди на изображении','map-select':'Работа с картой','drag-sort':'Расположи по порядку','timeline':'Лента времени','matching':'Соедини пару','classification':'Классификация','drag-to-scene':'Размести в зоне','find-the-mistake':'Найди ошибку','safe-route':'Безопасный маршрут','situation-choice':'Реши ситуацию','cause-effect':'Причина и следствие','sequence':'Восстанови последовательность','image-mission':'Исследуй изображение'};
  const storedContentVersion=Number(localStorage.getItem('worldContentVersion'))||0;if(storedContentVersion!==WorldMissionEngine.WORLD_CONTENT_VERSION){['worldCurrentAdventurePlan','worldLevelProgress','worldLevelRunStats'].forEach(key=>localStorage.removeItem(key));localStorage.setItem('worldContentVersion',String(WorldMissionEngine.WORLD_CONTENT_VERSION))}
  let plan=read('worldCurrentAdventurePlan',null),currentLevel=1,missionIndex=0,levelScore=0,levelCorrect=0,answered=false,soundOn=localStorage.getItem('magic-library-sound')!=='off',pendingGuardian=false,trailerMusicWasPlaying=false;
  function tone(kind){if(!soundOn)return;try{const AudioContext=window.AudioContext||window.webkitAudioContext,context=new AudioContext(),osc=context.createOscillator(),gain=context.createGain();osc.type=kind==='wrong'?'triangle':'sine';osc.frequency.value=kind==='correct'?660:kind==='reward'?520:230;gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.09,context.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.3);osc.connect(gain).connect(context.destination);osc.start();osc.stop(context.currentTime+.32);osc.onended=()=>context.close()}catch(_){}}
  function ensurePlan(force=false){if(force||!plan||!WorldMissionEngine.validateAdventurePlan(plan)){plan=WorldMissionEngine.buildAdventurePlan();write('worldCurrentAdventurePlan',plan);write('worldLevelProgress',{1:0,2:0,3:0,4:0});write('worldLevelRunStats',{})}return plan}
  function showCycleComplete(error){if(error?.code!=='WORLD_CURRICULUM_COMPLETE'&&error?.code!=='WORLD_INCOMPLETE_LEVEL_BANK'){console.error('[WORLD PLAN ERROR]',error);return false}console.info('[WORLD CURRICULUM]',error.message);$('.cycle-dialog').showModal();return true}
  function startNewAdventure(){try{ensurePlan(true);renderMap();tone('map');return true}catch(error){return showCycleComplete(error)}}
  function highest(){return Math.min(4,Math.max(1,Number(localStorage.getItem('worldHighestUnlockedLevel'))||1))}
  function completed(){return [...new Set(read('worldCompletedLevels',[]).map(Number).filter(level=>Number.isInteger(level)&&level>=1&&level<=4))].sort((a,b)=>a-b)}
  function unlockThrough(level){const current=highest(),next=Math.min(4,Math.max(current,Number(level)||1));if(next>current)localStorage.setItem('worldHighestUnlockedLevel',String(next));return next}
  function saveCompletedLevel(level){const done=[...new Set([...completed(),Number(level)])].filter(item=>Number.isInteger(item)&&item>=1&&item<=4).sort((a,b)=>a-b);write('worldCompletedLevels',done);return done}
  function reconcileUnlockProgress(){const done=completed();if(done.length)unlockThrough(Math.max(...done.map(level=>Math.min(4,level+1))));write('worldCompletedLevels',done)}
  function debugUnlock(){if(localStorage.getItem('worldDebugUnlock')==='true')console.log('[WORLD UNLOCK]',{highest:localStorage.getItem('worldHighestUnlockedLevel'),completed:completed()})}
  function levelProgress(){return read('worldLevelProgress',{1:0,2:0,3:0,4:0})}
  function renderMap(){const unlocked=highest(),done=completed(),progress=levelProgress(),best=read('worldBestResults',{});territories.replaceChildren();levelMeta.forEach((meta,index)=>{const level=index+1,locked=level>unlocked,button=document.createElement('button');button.type='button';button.className=`territory${locked?' locked':''}${done.includes(level)?' completed':''}`;button.disabled=locked;button.dataset.level=level;button.setAttribute('aria-label',`${meta.name}. ${locked?'Экспедиция закрыта':`Прогресс ${progress[level]||0} из 10`}`);button.innerHTML=`<img src="../assets/world-levels/${meta.image}" alt="" width="1448" height="1086"><span class="territory-number">${level}</span><span class="territory-chest" aria-hidden="true">${done.includes(level)?'✨':'🎁'}</span><div class="territory-copy"><span>Экспедиция ${level} · лучший результат ${best[level]||0}/10</span><h3>${meta.name}</h3><div class="territory-progress"><i><b style="width:${(progress[level]||0)*10}%"></b></i><strong>${progress[level]||0}/10</strong></div><span class="territory-status">${locked?'Территория ещё закрыта':done.includes(level)?'Экспедиция завершена':'Отправиться в путь'}</span></div>`;territories.append(button)});const fragments=Number(localStorage.getItem('worldMapFragments'))||0;$('#fragment-count').textContent=fragments;$('#guardian-slot').classList.toggle('unlocked',localStorage.getItem('worldGuardianUnlocked')==='true');$('#guardian-slot span').textContent=localStorage.getItem('worldGuardianUnlocked')==='true'?'🦉':'?'}
  function beginLevel(level){try{ensurePlan()}catch(error){showCycleComplete(error);return}currentLevel=level;const progress=levelProgress()[level]||0,stats=read('worldLevelRunStats',{});missionIndex=progress>=10?0:Math.min(progress,9);if(progress>=10){stats[level]={score:0,correct:0};const resetProgress=levelProgress();resetProgress[level]=0;write('worldLevelProgress',resetProgress)}while(missionIndex<10&&WorldMissionEngine.wasMissionSeen(plan.levels[level][missionIndex]))missionIndex+=1;if(missionIndex>=10){try{ensurePlan(true)}catch(error){showCycleComplete(error);return}missionIndex=0;stats[level]={score:0,correct:0}}const resumedProgress=levelProgress();resumedProgress[level]=missionIndex;write('worldLevelProgress',resumedProgress);write('worldLevelRunStats',stats);levelScore=stats[level]?.score||0;levelCorrect=stats[level]?.correct||0;mapScreen.classList.add('hidden');missionScreen.classList.remove('hidden');renderMission()}
  function startLevel(level){showMagicTransition({theme:'world',title:`ЭКСПЕДИЦИЯ ${level}\n${levelMeta[level-1].name.toUpperCase()}`,subtitle:'Маршрут открыт!',onComplete:()=>beginLevel(level)})}
  function renderMission(){answered=false;feedback.className='mission-feedback';feedback.replaceChildren();continueButton.hidden=true;let mission=plan.levels[currentLevel][missionIndex];if(WorldMissionEngine.wasMissionSeen(mission)){missionIndex+=1;if(missionIndex>=10){if(!startNewAdventure())return;missionIndex=0}const progress=levelProgress();progress[currentLevel]=missionIndex;write('worldLevelProgress',progress);return renderMission()}const meta=levelMeta[currentLevel-1];if(!WorldMissionEngine.recordMissionShown(mission))return renderMission();$('#mission-level').textContent=`Экспедиция ${currentLevel}`;$('#mission-name').textContent=meta.name;$('#mission-count').textContent=`Миссия ${missionIndex+1} из 10 · Общий путь ${(currentLevel-1)*10+missionIndex+1} / 40`;$('#mission-score').textContent=levelScore;const missionArt=$('.mission-art'),missionImage=$('#mission-image'),hasImage=Boolean(mission.image);missionArt.hidden=!hasImage;$('.mission-card').classList.toggle('no-art',!hasImage);if(hasImage){missionImage.src=mission.image;missionImage.alt=mission.imageAlt||`Тематическая карта задания: ${mission.question}`}else{missionImage.removeAttribute('src');missionImage.alt=''}$('#mechanic-label').textContent=mechanicNames[mission.mechanic]||mission.mechanic;$('#mission-question').textContent=mission.question;$('#mission-instruction').textContent=mission.instruction||'Выполни задание.';interaction.replaceChildren();renderInteraction(mission)}
  function button(label,className='choice-button'){const item=document.createElement('button');item.type='button';item.className=className;item.textContent=label;return item}
  function renderInteraction(mission){
    if(mission.payload.mode==='order'){const preview=document.createElement('p'),list=document.createElement('div'),selected=[];preview.className='order-preview';preview.textContent='Нажимай элементы в нужном порядке';list.className='order-list';mission.payload.items.forEach(label=>{const item=button(label,'order-item');item.draggable=true;item.addEventListener('click',()=>{if(answered||item.classList.contains('selected'))return;item.classList.add('selected');selected.push(label);preview.textContent=selected.join(' → ');if(selected.length===mission.payload.items.length)resolveMission(selected.join('|')===mission.payload.correctOrder.join('|'),item,mission)});item.addEventListener('dragstart',event=>event.dataTransfer.setData('text/plain',label));list.append(item)});interaction.append(preview,list);return}
    if(mission.payload.mode==='classify'){const wrap=document.createElement('div'),item=document.createElement('div');wrap.className='classification';item.className='classify-item';item.textContent=mission.payload.item;wrap.append(item);mission.payload.buckets.forEach(label=>{const target=button(label,'bucket');target.addEventListener('click',()=>resolveMission(label===mission.payload.correctBucket,target,mission));target.addEventListener('dragover',event=>event.preventDefault());target.addEventListener('drop',event=>{event.preventDefault();resolveMission(label===mission.payload.correctBucket,target,mission)});wrap.append(target)});interaction.append(wrap);return}
    if(mission.payload.mode==='match'){const prompt=document.createElement('div');prompt.className='matching-prompt';prompt.textContent='Подбери верное соответствие';interaction.append(prompt);mission.payload.options.forEach(label=>{const option=button(label,'match-option');option.addEventListener('click',()=>resolveMission(label===mission.correct,option,mission));interaction.append(option)});return}
    const wrapper=document.createElement('div');wrapper.className=`choice-grid mechanic-${mission.mechanic}`;mission.payload.options.forEach((label,index)=>{const option=button(`${['A','Б','В'][index]}. ${label}`);option.addEventListener('click',()=>resolveMission(label===mission.correct,option,mission));wrapper.append(option)});interaction.append(wrapper)
  }
  function resolveMission(correct,target,mission){if(answered)return;answered=true;target.classList.add(correct?'correct':'wrong');if(!correct){[...interaction.querySelectorAll('button')].find(item=>item.textContent.includes(mission.correct))?.classList.add('correct')}levelCorrect+=correct?1:0;levelScore+=correct?100:25;const stats=read('worldLevelRunStats',{});stats[currentLevel]={score:levelScore,correct:levelCorrect};write('worldLevelRunStats',stats);$('#mission-score').textContent=levelScore;WorldMissionEngine.recordResult(mission,correct);feedback.className=`mission-feedback show ${correct?'success':'soft-error'}`;feedback.innerHTML=`<strong>${correct?'Открытие сделано!':'Хорошая попытка!'}</strong><span>${mission.explanation}</span>`;continueButton.hidden=false;tone(correct?'correct':'wrong')}
  function advance(){if(!answered)return;if(missionIndex<9){missionIndex+=1;const progress=levelProgress();progress[currentLevel]=missionIndex;write('worldLevelProgress',progress);renderMission();return}completeLevel()}
  function completeLevel(){const best=read('worldBestResults',{});best[currentLevel]=Math.max(best[currentLevel]||0,levelCorrect);write('worldBestResults',best);const won=levelCorrect>=7,meta=levelMeta[currentLevel-1];$('#reward-correct').textContent=`${levelCorrect} / 10`;$('#reward-score').textContent=levelScore;const rewardDialog=$('.reward-dialog');if(!won){rewardDialog.classList.add('not-won');$('#reward-title').textContent='Экспедиция почти завершена';$('#reward-copy').textContent='Попробуй экспедицию ещё раз — новый маршрут уже ждёт.';$('.reward-continue').textContent='Вернуться на карту';rewardDialog.showModal();return}const done=completed(),first=!done.includes(currentLevel);saveCompletedLevel(currentLevel);unlockThrough(currentLevel+1);debugUnlock();if(first){const postcards=read('worldPostcards',{}),medals=read('worldMedals',{});postcards[currentLevel]=meta.postcard;medals[currentLevel]=meta.medal;write('worldPostcards',postcards);write('worldMedals',medals);if(currentLevel===4){localStorage.setItem('worldGuardianUnlocked','true');pendingGuardian=true}}else{const fragments=Number(localStorage.getItem('worldMapFragments'))||0,earned=levelCorrect===10?5:levelCorrect===9?3:levelCorrect===8?2:1,total=fragments+earned;localStorage.setItem('worldMapFragments',String(total));if(total>=10)localStorage.setItem('worldGoldenCompassUnlocked','true')}const progress=levelProgress();progress[currentLevel]=10;write('worldLevelProgress',progress);rewardDialog.className=`world-dialog reward-dialog reward-level-${currentLevel}`;$('#reward-title').textContent='Экспедиция завершена!';$('#reward-postcard').src=`../assets/world-levels/${meta.image}`;$('#reward-postcard').alt=`Коллекционная открытка «${meta.postcard}»`;$('#reward-medal').src=`../assets/world-rewards/${meta.medalImage}`;$('#reward-medal').alt=meta.medal;$('#postcard-name').textContent=first?meta.postcard:'ФРАГМЕНТЫ КАРТЫ';$('#medal-name').textContent=first?meta.medal:`+${levelCorrect===10?5:levelCorrect===9?3:levelCorrect===8?2:1} ФРАГМЕНТА`;$('#reward-copy').textContent=first?'Новые сокровища добавлены в Альбом экспедиций.':'Основная награда уже в альбоме — получены фрагменты карты.';$('.reward-continue').textContent='Продолжить путь';rewardDialog.showModal();tone('reward')}
  function renderAlbum(){const postcards=read('worldPostcards',{}),medals=read('worldMedals',{});$('#album-grid').replaceChildren();levelMeta.forEach((meta,index)=>{const level=index+1,postcardOwned=Boolean(postcards[level]),postcard=document.createElement('article');postcard.className=`album-item postcard${postcardOwned?'':' locked'}`;postcard.innerHTML=`<img src="../assets/world-levels/${meta.image}" alt=""><strong>${postcardOwned?postcards[level]:'???'}</strong><small>${postcardOwned?'Коллекционная открытка':'Открытка ещё не найдена'}</small>`;$('#album-grid').append(postcard);const medalOwned=Boolean(medals[level]),medal=document.createElement('article');medal.className=`album-item medal${medalOwned?'':' locked'}`;medal.innerHTML=`<img src="../assets/world-rewards/${meta.medalImage}" alt=""><strong>${medalOwned?medals[level]:'???'}</strong><small>${medalOwned?'Неоновая медаль':'Медаль ещё не открыта'}</small>`;$('#album-grid').append(medal)});const extras=[{owned:localStorage.getItem('worldGoldenCompassUnlocked')==='true',icon:'🧭',name:'Золотой компас'},{owned:localStorage.getItem('worldGuardianUnlocked')==='true',icon:'🦉',name:'Атлас — Хранитель Мира'}];extras.forEach(extra=>{const item=document.createElement('article');item.className=`album-item${extra.owned?'':' locked'}`;item.innerHTML=`<div style="font-size:78px">${extra.owned?extra.icon:'🔒'}</div><strong>${extra.owned?extra.name:'???'}</strong><small>${extra.owned?'Коллекция экспедиции':'Тайна ещё закрыта'}</small>`;$('#album-grid').append(item)})}
  function finishIntro(markSeen=true){const intro=$('#world-intro'),video=$('#world-intro-video');intro.classList.add('leaving');if(markSeen)localStorage.setItem('worldIntroSeen','true');setTimeout(()=>{video.pause();intro.hidden=true;intro.classList.remove('leaving','playing','waiting');if(trailerMusicWasPlaying&&soundOn)AdventureMusic.play();trailerMusicWasPlaying=false},450)}
  function prepareIntro(label='▶ Начать приключение'){const intro=$('#world-intro'),video=$('#world-intro-video'),start=$('.intro-start');intro.hidden=false;intro.classList.remove('leaving','playing');intro.classList.add('waiting');start.hidden=false;start.textContent=label;video.pause();video.currentTime=0;video.muted=true}
  function playIntro(){const intro=$('#world-intro'),video=$('#world-intro-video'),start=$('.intro-start');trailerMusicWasPlaying=soundOn;AdventureMusic.audio.pause();AdventureMusic.audio.volume=0;video.currentTime=0;video.volume=1;video.muted=!soundOn;const attempt=video.play();if(!attempt){finishIntro(false);return}attempt.then(()=>{start.hidden=true;intro.classList.remove('waiting');intro.classList.add('playing')}).catch(()=>{video.muted=true;start.hidden=false;start.textContent='▶ Включить видео';intro.classList.add('waiting');if(trailerMusicWasPlaying&&soundOn)AdventureMusic.play()})}
  territories.addEventListener('click',event=>{const territory=event.target.closest('.territory');if(territory&&!territory.disabled){tone('map');startLevel(Number(territory.dataset.level))}});continueButton.addEventListener('click',advance);$('.return-map').addEventListener('click',()=>{missionScreen.classList.add('hidden');mapScreen.classList.remove('hidden');renderMap()});$('.new-adventure').addEventListener('click',startNewAdventure);$('.watch-trailer').addEventListener('click',()=>{prepareIntro('▶ Смотреть трейлер');playIntro()});$('.intro-skip').addEventListener('click',()=>finishIntro(true));$('.intro-start').addEventListener('click',playIntro);$('#world-intro-video').addEventListener('ended',()=>finishIntro(true));$('#world-intro-video').addEventListener('error',()=>finishIntro(false));$('.album-button').addEventListener('click',()=>{renderAlbum();$('.album-dialog').showModal()});$('.album-close').addEventListener('click',()=>$('.album-dialog').close());$('.reward-continue').addEventListener('click',()=>{$('.reward-dialog').close();missionScreen.classList.add('hidden');mapScreen.classList.remove('hidden');renderMap();if(pendingGuardian){pendingGuardian=false;$('.guardian-dialog').showModal();tone('reward')}});$('.guardian-continue').addEventListener('click',()=>{$('.guardian-dialog').close();renderMap()});$('.reset-progress').addEventListener('click',()=>$('.reset-dialog').showModal());$('.cancel-reset').addEventListener('click',()=>$('.reset-dialog').close());$('.confirm-reset').addEventListener('click',()=>{Object.keys(localStorage).filter(key=>key.startsWith('world')).forEach(key=>localStorage.removeItem(key));plan=null;ensurePlan(true);localStorage.setItem('worldHighestUnlockedLevel','1');$('.reset-dialog').close();renderMap();prepareIntro()});$('.start-next-cycle').addEventListener('click',()=>{WorldMissionEngine.beginNextCycle();plan=null;ensurePlan(true);$('.cycle-dialog').close();renderMap();tone('map')});$('.close-cycle').addEventListener('click',()=>$('.cycle-dialog').close());$('.sound-toggle').addEventListener('click',event=>{soundOn=!soundOn;localStorage.setItem('magic-library-sound',soundOn?'on':'off');const introVideo=$('#world-intro-video');if(!$('#world-intro').hidden)introVideo.muted=!soundOn;event.currentTarget.textContent=soundOn?'🔊':'🔇';event.currentTarget.setAttribute('aria-pressed',String(soundOn));event.currentTarget.setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук')});$('.sound-toggle').textContent=soundOn?'🔊':'🔇';
  AdventureMusic.configure(.12);$('.sound-toggle').addEventListener('click',()=>setTimeout(()=>{if(!$('#world-intro').hidden){AdventureMusic.audio.pause();AdventureMusic.audio.volume=0}else AdventureMusic.syncWithSoundSetting()},0));WorldMissionEngine.loadPersistentWorldHistory();try{ensurePlan()}catch(error){showCycleComplete(error)}localStorage.setItem('worldHighestUnlockedLevel',String(highest()));reconcileUnlockProgress();debugUnlock();renderMap();WorldMissionEngine.getDebugStats();if(localStorage.getItem('worldIntroSeen')==='true')$('#world-intro').hidden=true;else prepareIntro();
})();
